services:
  ollama:
    build:
      context: ./docker/ollama/
    container_name: trans-ollama
    networks:
      - trans-network
    healthcheck:
      test: ["CMD-SHELL", "command ollama"]
      interval: 5s
      retries: 3
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: trans-web
    ports:
      - 8000:8000
    networks:
      - trans-network
    volumes:
      - ./:/app
    command: fastapi dev --host 0.0.0.0 app/main.py
    env_file:
      - .env.local
    depends_on:
      ollama:
        condition: service_healthy

networks:
  trans-network:
    external: false
